# Generated by Django 4.1.1 on 2022-09-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0004_remove_jadwal_detail_pelajaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_validasi', models.CharField(choices=[('Unlock', 'Unlock'), ('Lock', 'Lock')], default='Unlock', max_length=10, verbose_name='Status Validasi Jadwal')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('detail_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.detailmatapelajaran')),
                ('detail_waktu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.detailwaktu')),
                ('guru', models.ForeignKey(blank=True, default='- Belum Ada Pengajar -', on_delete=django.db.models.deletion.CASCADE, to='administrator.guru')),
                ('ruangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.ruangan')),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
                'ordering': ['published'],
            },
        ),
    ]
