# Generated by Django 4.1.1 on 2022-09-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0003_delete_revisijadwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisiJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisi_messages', models.TextField(max_length=500, verbose_name='Pesan Revisi untuk Jadwal')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jadwal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.jadwal')),
            ],
            options={
                'verbose_name_plural': 'Revisi Jadwal',
                'ordering': ['updated'],
            },
        ),
    ]
