# Generated by Django 4.1.1 on 2022-09-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Detail Kelas Peserta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailMataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jam', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total Jam Pelajaran')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kelas_peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.detailkelas')),
            ],
            options={
                'verbose_name_plural': 'Detail Mata Pelajaran',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailWaktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Detail Waktu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=15, unique=True, verbose_name='Nomor Induk Pegawai')),
                ('nama_lengkap', models.CharField(max_length=150, unique=True, verbose_name='Nama Lengkap Guru')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email Guru')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Guru',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10, unique=True, verbose_name='Nama Hari')),
            ],
            options={
                'verbose_name_plural': 'Hari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jalur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jalur', models.CharField(max_length=5, unique=True, verbose_name='Kode Unik Jalur')),
                ('nama_jalur', models.CharField(max_length=25, verbose_name='Nama Jalur')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jalur',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(choices=[('Kelas X', 'Kelas X'), ('Kelas XI', 'Kelas XI'), ('Kelas XII', 'Kelas XII')], max_length=12, unique=True, verbose_name='Nama Kelas')),
            ],
            options={
                'verbose_name_plural': 'Kelas',
                'ordering': ['nama_kelas'],
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=10, unique=True, verbose_name='Kode Mata Pelajaran (MU001)')),
                ('mapel', models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['kode_mapel'],
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_role', models.CharField(choices=[('Administrator', 'Administrator'), ('Pimpinan', 'Pimpinan'), ('TenagaPengajar', 'TenagaPengajar'), ('Siswa', 'Siswa')], max_length=20, unique=True, verbose_name='Role Pengguna')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Role User',
                'ordering': ['nama_role'],
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_ruangan', models.CharField(max_length=10, unique=True, verbose_name='Kode Ruangan (R01)')),
                ('nama_ruangan', models.CharField(max_length=50, unique=True, verbose_name='Nama Ruangan')),
                ('kapasitas_ruangan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kapasitas Ruangan')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ruangan',
                'ordering': ['kode_ruangan'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_user', models.CharField(max_length=20, unique=True, verbose_name='NIP atau Nomor Induk Siswa')),
                ('nama_lengkap', models.CharField(max_length=150, unique=True, verbose_name='Nama Lengkap User')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email User')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User',
                'ordering': ['kode_user'],
            },
        ),
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_waktu', models.CharField(max_length=30, unique=True, verbose_name='Rentang Waktu Pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Waktu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_validasi', models.CharField(choices=[('Unlock', 'Unlock'), ('Lock', 'Lock')], default='Unlock', max_length=10, verbose_name='Status Validasi Jadwal')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('detail_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.detailmatapelajaran')),
                ('detail_waktu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.detailwaktu')),
                ('guru', models.ForeignKey(blank=True, default='- Belum Ada Pengajar -', on_delete=django.db.models.deletion.CASCADE, to='administrator.guru')),
                ('ruangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.ruangan')),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
                'ordering': ['published'],
            },
        ),
        migrations.AddField(
            model_name='detailwaktu',
            name='hari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.hari'),
        ),
        migrations.AddField(
            model_name='detailwaktu',
            name='waktu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.waktu'),
        ),
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.roleuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.user')),
            ],
            options={
                'verbose_name_plural': 'Detail User',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='detailmatapelajaran',
            name='mapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.matapelajaran'),
        ),
        migrations.AddField(
            model_name='detailkelas',
            name='jalur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.jalur'),
        ),
        migrations.AddField(
            model_name='detailkelas',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.kelas'),
        ),
    ]
