# Generated by Django 4.1.1 on 2022-09-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waktu',
            options={'ordering': ['nama_waktu'], 'verbose_name_plural': 'Waktu'},
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='kode_mapel',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Mata Pelajaran'),
        ),
        migrations.CreateModel(
            name='RevisiJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisi_messages', models.TextField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jadwal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.jadwal')),
            ],
            options={
                'verbose_name_plural': 'Revisi Jadwal',
                'ordering': ['updated'],
            },
        ),
    ]
