# Generated by Django 4.1.1 on 2022-09-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_waktu_options_alter_matapelajaran_kode_mapel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevisiJadwal',
        ),
    ]
