# Generated by Django 4.1.1 on 2022-09-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_delete_revisijadwal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='detail_pelajaran',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='detail_waktu',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='guru',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='ruangan',
        ),
        migrations.AlterModelOptions(
            name='detailkelas',
            options={'ordering': ['kelas'], 'verbose_name_plural': 'Detail Kelas Peserta'},
        ),
        migrations.AlterModelOptions(
            name='detailwaktu',
            options={'ordering': ['waktu'], 'verbose_name_plural': 'Detail Waktu'},
        ),
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'ordering': ['id'], 'verbose_name_plural': 'Mata Pelajaran'},
        ),
    ]
