# Generated by Django 4.1.1 on 2022-10-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_delete_jadwal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailwaktu',
            options={'ordering': ['hari', 'waktu'], 'verbose_name_plural': 'Detail Waktu'},
        ),
    ]
